name: dialog2
description: Modern modal dialog implementation containing remakes of alert & confirm dialogs supplemented by prompt & custom modal dialogs
version: 0.7.2
homepage: https://github.com/catmaomao/dialog-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0
